version: "3.9"
services:
  product-container:
    container_name: product-ecomm
    build: ./product/
    ports:
      - 3001:3001
    volumes:
      - ./product/:/app/product
    environment:
      - JWT_SECRET=senhasecretadodocker
      - PORT=3001
      - DB_HOST=mongo-database
    depends_on:
      - mongo-database
  account-container:
    container_name: account-ecomm
    build: ./account/
    ports:
      - 3002:3002
    volumes:
      - ./account:/app/account
    environment:
      - JWT_SECRET=senhasecretadodocker
      - PORT=3002
      - DB_HOST=mongo-database
    depends_on:
      - mongo-database
  order-container:
    container_name: order-ecomm
    build: ./order/
    ports:
      - 3003:3003
    volumes:
      - ./order:/app/order
    environment:
      - JWT_SECRET=senhasecretadodocker
      - PORT=3003
      - DB_HOST=mysql-database
      - PAYMENT_HOST=finance-container
      - ACCOUNT_HOST=account-container
      - PRODUCT_HOST=product-container
    depends_on:
      - mysql-database
  finance-container:
    container_name: finance-ecomm
    build: ./finance/
    ports:
      - 3004:3004
    volumes:
      - ./finance:/app/finance
    environment:
      - JWT_SECRET=senhasecretadodocker
      - PORT=3004
      - DB_HOST=mysql-database
    depends_on:
      - mysql-database
  mongo-database:
    container_name: 'mongo-ecomm'
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-ecomm-volume:/var/lib/mysql
  mysql-database:
    container_name: 'mysql-ecomm'
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
  redis-database:
    container_name: 'redis_ecomm'
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-ecomm-volume:/data
  mysql-test-database:
    container_name: 'mysql-ecomm-test'
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  mongo-test-database:
    container_name: 'mongo-ecomm-test'
    image: mongo:5
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
volumes:
  mysql-ecomm-volume:
  mongo-ecomm-volume:
  redis-ecomm-volume: